app:
    resource: "@AppBundle/Controller/"
    type:     annotation
ayuda:
    path: /ayuda
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/ayuda.html.twig